listen: 0.0.0.0:443

# iptables -t nat -A PREROUTING -i eth0 -p udp --dport 10000:30000 -j REDIRECT --to-ports 443
# https://download.hysteria.network/app/latest/hysteria-linux-amd64
# bash <(curl â€“sL https://raw.githubusercontent.com/jabberwocky238/v2ray-tcp-tls-web/master/install.sh) && v2script


tls:
  cert: /etc/ssl/tls-shunt-proxy/certificates/acme-v02.api.letsencrypt.org-directory/DOMAINNAME/DOMAINNAME.crt
  key: /etc/ssl/tls-shunt-proxy/certificates/acme-v02.api.letsencrypt.org-directory/DOMAINNAME/DOMAINNAME.key

auth:
  type: http
  http:
    url: https://cf1.enzyme.cloud/api/proxy/auth
    insecure: false

masquerade:
  type: proxy
  proxy:
    url: https://google.com
    rewrite_host: true

bandwidth:
  up: 100 mbps
  down: 100 mbps
  ignoreClientBandwidth: true

trafficStats:
  listen: 0.0.0.0:39998
  secret: "Ae7RAuFZ8LzgAe7RAuFZ8LzgFUCKERSHITCO!@#!@#DDSSsdasdRTEX"
